# Numpy --- Numerical python

- A python package used for computing and processing single dim and multi dimesion array
- It is written in C
- An array can contain only homogeneous data

- NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently. This behavior is called locality of reference in computer science. This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

In [17]:
pip install numpy

In [18]:
import numpy as np
 
print("My numpy version is: ", np.__version__)

My numpy version is:  1.21.5


In [2]:
import time

In [3]:
lst_1 = range(10000000)
lst_2 = range(10000000)

initial = time.time()
e_list = []

for i,j in zip(lst_1 , lst_2):
    e_list.append(i+j)

time.time() - initial

4.396277189254761

In [4]:
import numpy as np

In [16]:
arr_1 = np.arange(10000000)
arr_2 = np.arange(10000000)

initial = time.time()

e_list = arr_1 + arr_2

time.time() - initial

0.26184892654418945

In [17]:
pip install numpy

In [6]:
import numpy as np

In [ ]:
math --> matrix
program --> arrays
deeplearnin --> tensors

# Creating an arrays

# Array function

In [5]:
import numpy as np
lst = [2,3,54,56,6]

arr = np.array(lst)

print(arr)

[ 2  3 54 56  6]


In [7]:
lst = [[2,3,4] , [5,6,7]] # 2d beacuse 2 brackets

arr = np.array(lst)

print(arr)

[[2 3 4]
 [5 6 7]]


In [8]:
lst = [[1,2], [6,7],[6,7],[6,7]] # 2 d matrix, row , column

arr = np.array(lst)

print(arr)


[[1 2]
 [6 7]
 [6 7]
 [6 7]]


In [9]:
lst = [[[1,2,3] , [4,5,6]] , [[7,8,9] , [10,11,12]]] # 3 d, depth, row, column

arr = np.array(lst)

print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [13]:
lst = [[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]] , [[7,8],[9,10],[11,12]]]

arr = np.array(lst)

print(arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [2]:
import numpy as np
lst = [[2,3,4] , [5,6,7]]

arr = np.array(lst)

print(arr)
print(arr.ndim)
print(arr.shape)

[[2 3 4]
 [5 6 7]]
2
(2, 3)


In [37]:
# A few import attributes 

# size --> total num of elements
print(arr.size)

# shape -->
print(arr.shape)

# ndim --> 

print(arr.ndim)

6
(2, 3)
2


In [19]:
lst = [[1,2], [6,7],[6,7],[6,7]]

arr = np.array(lst)

print(arr)


[[1 2]
 [6 7]
 [6 7]
 [6 7]]


In [20]:
print(arr.size)

# shape -->
print(arr.shape)

# ndim --> 

print(arr.ndim)

8
(4, 2)
2


In [41]:
lst = [[[1,2,3] , [4,5,6]] , [[7,8,9] , [10,11,12]]]

arr = np.array(lst)

print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [42]:
print(arr.size)

# shape --> depth , rows , column
print(arr.shape)

# ndim --> 

print(arr.ndim)

12
(2, 2, 3)
3


In [43]:
lst = [[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]] , [[7,8],[9,10],[11,12]]]

arr = np.array(lst)

print(arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [44]:
print(arr.size)

# shape --> depth , rows , column
print(arr.shape) # 3,3,2

# ndim --> 

print(arr.ndim)

18
(3, 3, 2)
3


# Arrange

In [53]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [54]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
list(range(2,10))

[2, 3, 4, 5, 6, 7, 8, 9]

In [56]:
list(range(2,10 , 2))

[2, 4, 6, 8]

In [22]:
np.arange(2,10 , 2)

array([2, 4, 6, 8])

In [60]:
list(range(5.5,11 ))

TypeError: 'float' object cannot be interpreted as an integer

In [61]:
np.arange(5.5 , 10.5)

array([5.5, 6.5, 7.5, 8.5, 9.5])

In [62]:
np.arange(5.5 , 10.5 , 0.5)

array([ 5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [67]:
np.arange('2024-05-28' , '2024-06-30' , 1 , dtype = 'datetime64')

array(['2024-05-28', '2024-05-29', '2024-05-30', '2024-05-31',
       '2024-06-01', '2024-06-02', '2024-06-03', '2024-06-04',
       '2024-06-05', '2024-06-06', '2024-06-07', '2024-06-08',
       '2024-06-09', '2024-06-10', '2024-06-11', '2024-06-12',
       '2024-06-13', '2024-06-14', '2024-06-15', '2024-06-16',
       '2024-06-17', '2024-06-18', '2024-06-19', '2024-06-20',
       '2024-06-21', '2024-06-22', '2024-06-23', '2024-06-24',
       '2024-06-25', '2024-06-26', '2024-06-27', '2024-06-28',
       '2024-06-29'], dtype='datetime64[D]')

In [68]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# Zero , zero like

In [69]:
np.zeros((2,5)) # 2 rows, 5 columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [74]:
np.zeros((3,5,8) , dtype = int)

array([[[0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]]])

In [28]:
np.zeros((3,5,8) , dtype = int)
#in the zeros method we are creating a new array of our desired shape and data type 
#having all the values as 0. But, here, we are directly passing an array or an array-
#like object to get an array of the same shape and data type.19


array([[[0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]]])

In [75]:
lst = [[[1,2,3] , [4,5,6]] , [[7,8,9] , [10,11,12]]]

arr = np.array(lst)

print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [29]:
print(np.zeros_like(arr))


[[0 0]
 [0 0]
 [0 0]
 [0 0]]


In [77]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [80]:
c = np.zeros_like(a)

In [81]:
c

array([0, 0, 0, 0])

In [82]:
np.add(a,b,c)

array([ 6,  8, 10, 12])

In [83]:
c

array([ 6,  8, 10, 12])

# Ones , Ones like

In [85]:
np.ones((2,3) , dtype = int)

array([[1, 1, 1],
       [1, 1, 1]])

In [86]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [87]:
np.ones_like(arr)

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

# Identity
rows = columns

dia = 1 and rest all 0

In [88]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Random

In [93]:
np.random.rand(2,5)

array([[0.77883555, 0.69711092, 0.98713668, 0.1722151 , 0.11761203],
       [0.3382612 , 0.28362089, 0.45436882, 0.145053  , 0.27414366]])

In [14]:
np.random.randn(5,5)

array([[ 1.85425225, -0.80799614, -1.22036513, -1.00133351,  0.56374262],
       [-1.92857608, -0.72382261, -1.11847395, -1.27873003, -1.24334417],
       [-1.35035291, -0.35698753, -0.73668023, -2.02527646, -0.44601248],
       [-0.8370312 ,  1.03503697, -1.98489507, -1.57530078,  0.21943079],
       [ 1.19093386, -1.22805209, -1.75747549,  1.66066237, -1.00148601]])

In [13]:
np.random.randint(5,10)

5

In [8]:
np.random.randint(1,7)

5

In [126]:
np.random.randint(1,7 , size = (3,5))

array([[4, 1, 1, 5, 5],
       [4, 2, 1, 5, 2],
       [4, 2, 6, 3, 5]])

In [127]:
np.random.randint(400 , 500)

487

# Remaining functions

In [138]:
while True:
    a = np.random.randint(1 , 100)
    print(a)
    if a == 50:
        break

67
18
48
25
28
22
6
2
17
66
48
59
81
50


In [ ]:
lst = ['emp_132' , '254emp_' , 'emp87687_' , 'emp_87687']

